<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-4KADTEQ" failures="1" tests="4" name="Test1" time="345.662" errors="0" timestamp="2023-04-04T14:59:56 IST">
  <testcase classname="testing.dev.BuyerPortalSignUpTest" name="signUpPageTest1" time="35.009"/>
  <testcase classname="testing.dev.BuyerPortalSignUpTest" name="signupPageTest3" time="30.161">
    <failure type="java.lang.AssertionError" message="expected [Email address already exists with another user account] but found []">
      <![CDATA[java.lang.AssertionError: expected [Email address already exists with another user account] but found []
at buyerportal.dev.ReusableFunction.assertion(ReusableFunction.java:229)
at buyerportal.dev.BuyerPortal_SignUp.signUp(BuyerPortal_SignUp.java:137)
at testing.dev.BuyerPortalSignUpTest.signupPageTest3(BuyerPortalSignUpTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- signupPageTest3 -->
  <testcase classname="testing.dev.BuyerPortalSignUpTest" name="signUpPageTest4" time="181.409"/>
  <testcase classname="testing.dev.BuyerPortalSignUpTest" name="signUpPageTest5" time="92.263"/>
  <testcase classname="testing.dev.BuyerPortalSignUpTest" name="signUpPageTest2" time="0.0">
    <ignored/>
  </testcase> <!-- signUpPageTest2 -->
</testsuite> <!-- Test1 -->
